[package]
name = "alien"
version = "0.1.0"
authors = ["Nikita Lyubchich <nikita.lyubchich@gmail.com>"]

[dependencies]
telegram-bot = "0.5.0"
hyper = "0.10.10"
serde = "1.0.7"
serde_json = "1.0.2"
serde_derive = "1.0.7"
toml = "0.4.1"
clippy = {version = "*", optional = true}
